// Implements specs/design/components/todo-api/openapi.yaml exactly -- same
// paths, schemas and status codes. Generated by `bal openapi --mode service`
// and then filled in: every resource resolves the caller from the gateway's
// verified assertion (never a client-supplied id) and scopes every read and
// write to that caller's own rows. The gateway already enforced each
// operation's scope, so no handler here re-checks one.
import ballerina/constraint;
import ballerina/http;
import ballerina/time;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todos
    #
    # + return - returns can be any of following types
    # http:Ok (A page of the caller's todos)
    # http:Unauthorized (Not signed in)
    resource function get me/todos(http:RequestContext ctx, boolean? completed, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        record {| TodoRow[] items; int total; |} page = check listTodos(caller.userId, 'limit, offset, completed);
        Todo[] data = from TodoRow row in page.items
            select toTodo(row);
        int nextOffset = offset + 'limit;
        int prevOffset = offset - 'limit;
        string? next = nextOffset < page.total ? pageUri('limit, nextOffset, completed) : ();
        string? previous = offset > 0 ? pageUri('limit, prevOffset > 0 ? prevOffset : 0, completed) : ();
        return {count: page.total, next, previous, data};
    }

    # A single one of the caller's todos
    #
    # + return - returns can be any of following types
    # http:Ok (The todo)
    # http:NotFound (No such todo for this caller)
    # http:Unauthorized (Not signed in)
    resource function get me/todos/[string todoId](http:RequestContext ctx) returns Todo|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        TodoRow? row = check getTodo(caller.userId, todoId);
        if row is () {
            return notFoundError();
        }
        return toTodo(row);
    }

    # Create a todo for the caller
    #
    # + return - returns can be any of following types
    # http:Created (The created todo)
    # http:BadRequest (Invalid todo)
    # http:Unauthorized (Not signed in)
    resource function post me/todos(http:RequestContext ctx, @http:Payload NewTodo payload)
            returns Todo|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        string title = payload.title.trim();
        if title == "" {
            return badRequestError("title must not be empty");
        }
        TodoRow row = check createTodo(caller.userId, title);
        return toTodo(row);
    }

    # Mark the caller's todo complete or reopen it
    #
    # + return - returns can be any of following types
    # http:Ok (The updated todo)
    # http:NotFound (No such todo for this caller)
    # http:Unauthorized (Not signed in)
    resource function put me/todos/[string todoId]/completion(http:RequestContext ctx, @http:Payload todoId_completion_body payload)
            returns Todo|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        TodoRow? row = check setTodoCompletion(caller.userId, todoId, payload.completed);
        if row is () {
            return notFoundError();
        }
        return toTodo(row);
    }
}

# + row - the persisted row
# + return - the contract's `Todo` shape
function toTodo(TodoRow row) returns Todo {
    return {
        id: row.id,
        title: row.title,
        completed: row.completed,
        createdAt: time:utcToString(row.created_at),
        updatedAt: time:utcToString(row.updated_at)
    };
}

# A relative URI for another page of `GET /me/todos`, preserving the filter.
#
# + 'limit - page size
# + offset - the other page's offset
# + completed - the filter in effect, if any
# + return - the relative URI
function pageUri(int 'limit, int offset, boolean? completed) returns string {
    string uri = string `/me/todos?limit=${'limit}&offset=${offset}`;
    if completed is boolean {
        uri = uri + "&completed=" + completed.toString();
    }
    return uri;
}

function unauthorizedError() returns ErrorUnauthorized {
    return {body: {code: 401, message: "not signed in"}};
}

function notFoundError() returns ErrorNotFound {
    return {body: {code: 404, message: "no such todo for this caller"}};
}

function badRequestError(string message) returns ErrorBadRequest {
    return {body: {code: 400, message}};
}

public type Todo record {
    string id;
    string title;
    boolean completed;
    string createdAt;
    string updatedAt?;
};

public type NewTodo record {
    @constraint:String {minLength: 1}
    string title;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type todoId_completion_body record {
    boolean completed;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
